version: "3.9"

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - fpm
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
    volumes:
      - ./.Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    links:
        - fpm

  fpm:
    build:
      context: ./.Docker/php
      dockerfile: Dockerfile
    image: transfer_app
    container_name: fpm
    working_dir: /app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
    volumes:
      - ./:/app
